---
# This playbook deploys a simple standalone Tomcat 8 server. 

- hosts: '{{target_host}}'
  user: root
  vars: 
    jdk_version: openjdk-8-jdk
    # http://apache.osuosl.org/tomcat/tomcat-8/v8.5.29/bin/apache-tomcat-8.5.29-fulldocs.tar.gz	
    tomcat_mirrors: http://apache.osuosl.org
    # Following is working mirror before..
    tomcat_major_version: tomcat-8
    tomcat_version: 8.5.29
    #supervisord_conf_path: /opt/python27env/supervisor/conf.d
    #ansible_python_interpreter: /opt/python27env/bin/python
    tomcat_group: www
    tomcat_user: www
    supervisor_service_name: supervisor
    supervisor_conf_root: '/etc/supervisor'
    supervisor_http_host: 0.0.0.0
    supervisor_http_port: 9001
    supervisor_http_user_name: admin
    supervisor_http_user_password: admin
  roles:
#    - selinux
    - jdk
    - supervisor
    - tomcat
    - deploy-war

